### ISSUE TITLE
Cannot call manifest-tool on command line when installed from pip

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/manifest-tool#11]
### Description
`manifest-tool` is not recognized as a valid executable when installed through pip. Tested on both Windows and Linux

### Steps to recreate the issue
```
> pip install -U manifest-tool
> manifest-tool
'manifest-tool' is not recognized as an internal or external command,
operable program or batch file.
```

### Background 

- I have confirmed my path variable is correct.  It includes the path to pip packages.  
    - `C:\Users\xxxxxxx\AppData\Roaming\Python\Python37\Scripts`
- After installation, there is a `manifest-tool` file present with no file extension in that location.  It is a python file.  
- Other packages installed with pip can be accessed with no problems.  They have .exe executable files in that location that can be called directly.  these include `pip.exe`, `pyocd.exe`, etc.  
- I have confirmed that the system can locate `manifest-tool` using the windows `where` command, it is just not an executable. 
    ```
    > where manifest-tool
    > C:\Users\xxxxxx\AppData\Roaming\Python\Python37\Scripts\manifest-tool
    ```

### Environment
- manifest-tool 1.5.2
- Windows 10 
- Python 3

### Impact
Multiple users have reported this.  

## Workaround

Install from source. 
```
> git clone https://github.com/armmbed/manifest-tool
> cd manifest-tool
> pip install . --user
> manifest-tool
usage: manifest-tool [-h] [-l {debug,info,warning,exception}] [--version]
                     {create,parse,verify,cert,init,sign,update} ...
```

**Comment by OPpuolitaival** [comment]
I did see same in linux

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTUC-1287

**Comment by alzix** [comment]
cannot reproduce it on either of my Linux, Windows and MacOS machines.
```
C:\Users\User>where manifest-tool
C:\Python37\Scripts\manifest-tool.exe
```
same for linux - please check your Python installation perhaps upgrading to latest version of Python and `pip` package can help.

**Comment by alzix** [comment]
Please make sure your PATH contains directories used by Python to install the entry point scripts.
Refer to this [thread](https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line)
